# 本文件采用 TOML 格式 https://toml.io/
# 以下项目的含义及其填写方法详见 https://github.com/ahui2016/R2-Gallery

# 可修改, 通常留空
author="{{album.author}}"

# 可修改
notes = '''
{{album.notes}}
'''

# 可修改
story = '''
{{album.story}}
'''

# 可修改, 请选择: 'CTime' / 'CTimeDesc' / 'List'
sort_by = '{{album.sort_by}}'

# 可修改
pictures = [
{% for pic in album.pictures %}
    '{{pic}}',
{%- endfor %}
]

# 可修改
cover = '{{album.cover}}'

# 可修改. 请选择: 'Story' / 'Single' / 'List'
frontpage = '{{album.frontpage}}'

# 请勿修改 checksum
checksum = '{{album.checksum}}'

